import { getAllPosts } from "@/api/post";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Card, CardHeader, CardBody, Skeleton } from "@nextui-org/react";
export const metadata: Metadata = {
  title: " NextJs Post Page",
  description: "Generated by create next app",
  openGraph: {
    title: " NextJs Post Page",
    description: "Generated by create next app",
  },
};

export default async function Post() {
  const posts = await getAllPosts();

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Post Page 1</h1>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        {posts.map((item: any) => {
          return (
            <Link href={"/post/" + item.id} key={item.id}>
              <Card className="py-4 border rounded-lg">
                <CardHeader className="pb-0 pt-2 px-4 flex-col items-start">
                  <p className="text-tiny uppercase font-bold">
                    {item.content}
                  </p>
                  <small className="text-default-500">{item.content}</small>
                  <h4 className="font-bold text-large">{item.name}</h4>
                </CardHeader>
                <CardBody className="overflow-visible py-2">
                  <Image
                    layout="responsive"
                    alt="Card background"
                    className="object-cover rounded-xl"
                    src={item.image as string}
                    width={270}
                    height={150}
                  />
                </CardBody>
              </Card>
            </Link>
          );
        })}
      </div>
    </main>
  );
}
